name: Deploy Code to Home Server
on:
  push:
    branches: [main]
    
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to server
      uses: actions/checkout@v2
