name: Deploy Code
on:
  push:
    branches: [main]
    
  workflow_dispatch:
  
jobs:
  cloud:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Deploy to Glitch
      if: ${{ matrix.os }} == 'ubuntu-latest'
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/irwindoug/hackit.pro.git"
        SOURCE_BRANCH: "main"
        DESTINATION_REPO: ${{ secrets.glitch_git_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
    
  home:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'var/www/hackit.pro'
    steps:
      - name: Deploy to server
        uses: actions/checkout@v2